!!ARBvp1.0
# ARB_vertex_program generated by NVIDIA Cg compiler
# cgc version 1.1.0003, build date Jul  7 2003  12:21:41
# command line args: -entry main_vp -profile arbvp1
# nv30vp backend compiling 'main_vp' program
PARAM c7 = { 0, 1, 0, 0 };
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbvp1
#program main_vp
#semantic main_vp.lightPosition
#semantic main_vp.eyePosition
#semantic main_vp.shininess
#semantic main_vp.worldViewProj
#var float4 position : $vin.POSITION : POSITION : 0 : 1
#var float3 normal : $vin.NORMAL : NORMAL : 1 : 1
#var float4 oPosition : $vout.POSITION : POSITION : 2 : 1
#var float diffuse : $vout.TEXCOORD0 : TEXCOORD0 : 3 : 1
#var float specular : $vout.TEXCOORD1 : TEXCOORD1 : 4 : 1
#var float edge : $vout.TEXCOORD2 : TEXCOORD2 : 5 : 1
#var float3 lightPosition :  : c[0] : 6 : 1
#var float3 eyePosition :  : c[1] : 7 : 1
#var float4 shininess :  : c[2] : 8 : 1
#var float4x4 worldViewProj :  : c[3], 4 : 9 : 1
TEMP R0, R1, R2, R3, R4;
ATTRIB v18 = vertex.normal;
ATTRIB v16 = vertex.position;
PARAM c2 = program.local[2];
PARAM c1 = program.local[1];
PARAM c0 = program.local[0];
PARAM c3[4] = { program.local[3..6] };
	DP4 result.position.x, c3[0], v16;
	DP4 result.position.y, c3[1], v16;
	DP4 result.position.z, c3[2], v16;
	DP4 result.position.w, c3[3], v16;
	DP3 R0.x, v18.xyzx, v18.xyzx;
	RSQ R0.x, R0.x;
	MUL R1.xyz, R0.x, v18.xyzx;
	ADD R0.yzw, c0.xxyz, -v16.xxyz;
	DP3 R0.x, R0.yzwy, R0.yzwy;
	RSQ R0.x, R0.x;
	MUL R4.xyz, R0.x, R0.yzwy;
	DP3 R0.x, R1.xyzx, R4.xyzx;
	MAX R0.x, R0.x, c7.x;
	MOV result.texcoord[0].x, R0.x;
	SGE R0.y, R0.x, c7.x;
	SGE R0.x, c7.x, R0.x;
	MUL R0.y, R0.y, R0.x;
	ADD R0.x, c7.y, -R0.y;
	ADD R2.xyz, c1.xyzx, -v16.xyzx;
	DP3 R0.z, R2.xyzx, R2.xyzx;
	RSQ R0.z, R0.z;
	MUL R3.xyz, R0.z, R2.xyzx;
	ADD R2.xyz, R4.xyzx, R3.xyzx;
	DP3 R0.z, R2.xyzx, R2.xyzx;
	RSQ R0.z, R0.z;
	MUL R2.xyz, R0.z, R2.xyzx;
	DP3 R0.z, R1.xyzx, R2.xyzx;
	MAX R2.xy, R0.z, c7.x;
	MOV R2.zw, c2.x;
	LIT R0.z, R2;
	MUL R0.x, R0.x, R0.z;
	MAD result.texcoord[1].x, R0.y, c7.x, R0.x;
	DP3 R0.x, R1.xyzx, R3.xyzx;
	MAX result.texcoord[2].x, R0.x, c7.x;
END
# 34 instructions
# 5 temp registers
# End of program
