!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.1.0003, build date Jul  7 2003  12:21:41
# command line args: -entry main_fp -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main_fp
#semantic main_fp.diffuse
#semantic main_fp.specular
#semantic main_fp.diffuseRamp
#semantic main_fp.specularRamp
#semantic main_fp.edgeRamp
#var float diffuseIn : $vin.TEXCOORD0 : TEXCOORD0 : 0 : 1
#var float specularIn : $vin.TEXCOORD1 : TEXCOORD1 : 1 : 1
#var float edge : $vin.TEXCOORD2 : TEXCOORD2 : 2 : 1
#var float4 colour : $vout.COLOR : COLOR : 3 : 1
#var float4 diffuse :  : c[0] : 4 : 1
#var float4 specular :  : c[1] : 5 : 1
#var sampler1D diffuseRamp :  : texunit 0 : 6 : 1
#var sampler1D specularRamp :  : texunit 1 : 7 : 1
#var sampler1D edgeRamp :  : texunit 2 : 8 : 1
PARAM u0 = program.local[0];
PARAM u1 = program.local[1];
TEMP R0;
TEMP R1;
TEX R0.x, fragment.texcoord[1].x, texture[1], 1D;
TEX R1.x, fragment.texcoord[0].x, texture[0], 1D;
MUL R0, u1, R0.x;
MAD R0, u0, R1.x, R0;
TEX R1.x, fragment.texcoord[2].x, texture[2], 1D;
MUL result.color, R1.x, R0;
END
# 6 instructions, 2 R-regs, 0 H-regs.
# End of program
