!!ARBvp1.0
# ARB_vertex_program generated by NVIDIA Cg compiler
# cgc version 1.1.0003, build date Jul  7 2003  12:21:41
# command line args: -profile arbvp1 -entry ambientOneTexture_vp
# nv30vp backend compiling 'ambientOneTexture_vp' program
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbvp1
#program ambientOneTexture_vp
#semantic ambientOneTexture_vp.worldViewProj
#semantic ambientOneTexture_vp.ambient
#var float4 position : $vin.POSITION : POSITION : 0 : 1
#var float2 uv : $vin.TEXCOORD0 : TEXCOORD0 : 1 : 1
#var float4 oPosition : $vout.POSITION : POSITION : 2 : 1
#var float2 oUv : $vout.TEXCOORD0 : TEXCOORD0 : 3 : 1
#var float4 colour : $vout.COLOR : COLOR : 4 : 1
#var float4x4 worldViewProj :  : c[0], 4 : 5 : 1
#var float4 ambient :  : c[4] : 6 : 1
ATTRIB v24 = vertex.texcoord[0];
ATTRIB v16 = vertex.position;
PARAM c4 = program.local[4];
PARAM c0[4] = { program.local[0..3] };
	MOV result.texcoord[0].xy, v24;
	DP4 result.position.x, c0[0], v16;
	DP4 result.position.y, c0[1], v16;
	DP4 result.position.z, c0[2], v16;
	DP4 result.position.w, c0[3], v16;
	MOV result.color.front.primary, c4;
END
# 6 instructions
# 0 temp registers
# End of program
