include ../../../platform-settings

all:
	$(CXX) $(DEFINES) $(CFLAGS) -o ParticleFX ParticleFX.cpp $(INCDIRS) -I$(TOPDIR)/Samples/Common/include -L$(TOPDIR)/OgreMain/lib -lOgreMain

clean:
	rm -f ParticleFX
