!!ARBvp1.0
# ARB_vertex_program generated by NVIDIA Cg compiler
# cgc version 1.1.0003, build date Mar  4 2003  12:32:10
# command line args: -profile arbvp1 -entry hardwareSkinningFourWeights_vp
# nv30vp backend compiling 'hardwareSkinningFourWeights_vp' program
PARAM c81 = { 0, 0, 0, 1 };
PARAM c82 = { 3, 2, 4, 0 };
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbvp1
#program hardwareSkinningFourWeights_vp
#semantic hardwareSkinningFourWeights_vp.worldMatrix3x4Array
#semantic hardwareSkinningFourWeights_vp.viewProjectionMatrix
#semantic hardwareSkinningFourWeights_vp.objectSpaceLightPos
#semantic hardwareSkinningFourWeights_vp.lightDiffuseColour
#semantic hardwareSkinningFourWeights_vp.ambient
#var float4 position : $vin.POSITION : POSITION : 0 : 1
#var float3 normal : $vin.NORMAL : NORMAL : 1 : 1
#var float2 uv : $vin.TEXCOORD0 : TEXCOORD0 : 2 : 1
#var float4 blendIdx : $vin.BLENDINDICES : BLENDINDICES : 3 : 1
#var float4 blendWgt : $vin.BLENDWEIGHT : BLENDWEIGHT : 4 : 1
#var float4 oPosition : $vout.POSITION : POSITION : 5 : 1
#var float2 oUv : $vout.TEXCOORD0 : TEXCOORD0 : 6 : 1
#var float4 colour : $vout.COLOR : COLOR : 7 : 1
#var float3x4 worldMatrix3x4Array[0] :  : c[0], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[1] :  : c[3], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[2] :  : c[6], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[3] :  : c[9], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[4] :  : c[12], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[5] :  : c[15], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[6] :  : c[18], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[7] :  : c[21], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[8] :  : c[24], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[9] :  : c[27], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[10] :  : c[30], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[11] :  : c[33], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[12] :  : c[36], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[13] :  : c[39], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[14] :  : c[42], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[15] :  : c[45], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[16] :  : c[48], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[17] :  : c[51], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[18] :  : c[54], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[19] :  : c[57], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[20] :  : c[60], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[21] :  : c[63], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[22] :  : c[66], 3 : 8 : 1
#var float3x4 worldMatrix3x4Array[23] :  : c[69], 3 : 8 : 1
#var float4x4 viewProjectionMatrix :  : c[72], 4 : 9 : 1
#var float3 objectSpaceLightPos[0] :  : c[76] : 10 : 1
#var float3 objectSpaceLightPos[1] :  : c[77] : 10 : 1
#var float4 lightDiffuseColour[0] :  : c[78] : 11 : 1
#var float4 lightDiffuseColour[1] :  : c[79] : 11 : 1
#var float4 ambient :  : c[80] : 12 : 1
TEMP R0, R1, R2, R3, R4, R5, R6;
ADDRESS A0;
ATTRIB v17 = vertex.weight;
ATTRIB v7 = vertex.attrib[7];
ATTRIB v24 = vertex.texcoord[0];
ATTRIB v18 = vertex.normal;
ATTRIB v16 = vertex.position;
PARAM c78[2] = { program.local[78..79] };
PARAM c80 = program.local[80];
PARAM c76[2] = { program.local[76..77] };
PARAM c72[4] = { program.local[72..75] };
PARAM c0[72] = { program.local[0..71] };
	MOV result.texcoord[0].xy, v24;
	FLR R0, v7;
	MUL R2, R0, c82.x;
	ARL A0.x, R2.w;
	DP4 R4.x, c0[A0.x], v16;
	DP4 R4.y, c0[A0.x + 1], v16;
	DP4 R4.z, c0[A0.x + 2], v16;
	MOV R4.w, c81.wxxw;
	ARL A0.x, R2.z;
	DP4 R3.x, c0[A0.x], v16;
	DP4 R3.y, c0[A0.x + 1], v16;
	DP4 R3.z, c0[A0.x + 2], v16;
	MOV R3.w, c81.wxxw;
	ARL A0.x, R2.y;
	DP4 R1.x, c0[A0.x], v16;
	DP4 R1.y, c0[A0.x + 1], v16;
	DP4 R1.z, c0[A0.x + 2], v16;
	MOV R1.w, c81.wxxw;
	ARL A0.x, R2.x;
	DP4 R0.x, c0[A0.x], v16;
	DP4 R0.y, c0[A0.x + 1], v16;
	DP4 R0.z, c0[A0.x + 2], v16;
	MOV R0.w, c81.wxxw;
	MAD R0, R0, v17.x, c81.xxxw;
	MAD R0, R1, v17.y, R0;
	MAD R0, R3, v17.z, R0;
	MAD R1, R4, v17.w, R0;
	DP4 result.position.x, c72[0], R1;
	DP4 result.position.y, c72[1], R1;
	DP4 result.position.z, c72[2], R1;
	DP4 result.position.w, c72[3], R1;
	ADD R0.yzw, c76[1].xxyz, -R1.xxyz;
	DP3 R0.x, R0.yzwy, R0.yzwy;
	RSQ R0.x, R0.x;
	MUL R0.xyz, R0.x, R0.yzwy;
	ARL A0.x, R2.w;
	DP3 R6.x, c0[A0.x].xyzx, v18.xyzx;
	DP3 R6.y, c0[A0.x + 1].xyzx, v18.xyzx;
	DP3 R6.z, c0[A0.x + 2].xyzx, v18.xyzx;
	ARL A0.x, R2.z;
	DP3 R5.x, c0[A0.x].xyzx, v18.xyzx;
	DP3 R5.y, c0[A0.x + 1].xyzx, v18.xyzx;
	DP3 R5.z, c0[A0.x + 2].xyzx, v18.xyzx;
	ARL A0.x, R2.x;
	DP3 R4.x, c0[A0.x].xyzx, v18.xyzx;
	DP3 R4.y, c0[A0.x + 1].xyzx, v18.xyzx;
	DP3 R4.z, c0[A0.x + 2].xyzx, v18.xyzx;
	ARL A0.x, R2.y;
	DP3 R3.x, c0[A0.x].xyzx, v18.xyzx;
	DP3 R3.y, c0[A0.x + 1].xyzx, v18.xyzx;
	DP3 R3.z, c0[A0.x + 2].xyzx, v18.xyzx;
	MUL R2.xyz, R3.xyzx, v17.y;
	MAD R2.xyz, R4.xyzx, v17.x, R2.xyzx;
	MAD R2.xyz, R5.xyzx, v17.z, R2.xyzx;
	MAD R2.xyz, R6.xyzx, v17.w, R2.xyzx;
	DP3 R0.w, R2.xyzx, R2.xyzx;
	RSQ R0.w, R0.w;
	MUL R2.yzw, R0.w, R2.xxyz;
	DP3 R0.x, R0.xyzx, R2.yzwy;
	MIN R0.x, c81.w, R0.x;
	MAX R2.x, c81.x, R0.x;
	ADD R0.yzw, c76[0].xxyz, -R1.xxyz;
	DP3 R0.x, R0.yzwy, R0.yzwy;
	RSQ R0.x, R0.x;
	MUL R0.xyz, R0.x, R0.yzwy;
	DP3 R0.x, R0.xyzx, R2.yzwy;
	MIN R0.x, c81.w, R0.x;
	MAX R1.x, c81.x, R0.x;
	MOV R0, c78[0];
	MAD R0, R1.x, R0, c80;
	MAD result.color.front.primary, R2.x, c78[1], R0;
END
# 71 instructions
# 7 temp registers
# End of program
