rollout unnamedRollout "Untitled" width:280 height:224
(
	button btn3 "Export" pos:[216,192] width:48 height:24
	button btn4 "Cancel" pos:[160,192] width:48 height:24
	editText edt13 "File:" pos:[16,64] width:248 height:20
	label debugLabel "Note: Debug information pertaining to the export will be written to the MaxScript listener and a log file within the 3dsmax directory." pos:[16,136] width:248 height:40
	button btn15 "Choose File..." pos:[176,96] width:88 height:24
	dropDownList staticMeshDropdown "Select editable mesh" pos:[16,8] width:248 height:40 enabled:true
)