#!/bin/sh

FOLDERS="Bezier BSP CameraTrack EnvMapping Gui Lighting Nature ParticleFX RenderToTexture SkeletalAnimation SkyBox SkyDome SkyPlane Terrain TextureFX Transparency CubeMapping Water Dot3Bump"

for myFolder in $FOLDERS
do
	cd $myFolder
	xcodebuild clean
	rm -r build
	
	if [ $? -ne 0 ] 
	then
  		break
	fi 
	
	cd ..
done


