include ../../../platform-settings

all:
	$(CXX) $(DEFINES) $(CFLAGS) -o TextureFX TextureFX.cpp $(INCDIRS) -I$(TOPDIR)/Samples/Common/include -L$(TOPDIR)/OgreMain/lib -lOgreMain

clean:
	rm -f TextureFX
